lane :test do
  android_sdk_update(
    compile_sdk_version: "27",
    build_tools_version: "27.0.2",
    additional_packages: ["extras;google;m2repository", "extras;android;m2repository"]
  )
  adb_devices
end
